sudo: required
dist: xenial
services:
  - xvfb

branches:
  only:
  - master
  - major
  - stable
  - latest
  - /^\d+\.\d+(\.\d+)?(-\S*)?$/
  - /^release\/\d+\.\d+\.x$/

language: node_js

node_js:
  - 10

env:
  - BROWSER=Chrome
  - BROWSER=Firefox MOZ_HEADLESS=1

addons:
  firefox: "latest"
  chrome: stable

before_script:
  # Prepare environment.
  - 'npm install benderjs-cli -g'
  - 'export DISPLAY=:99.0'
  - 'sleep 3'

script:
  - 'BUILD_PATH=0'
  - 'bash ./build.sh full all -t'
  - 'BUILD_PATH="$(sh -e ./dev/travis/buildpath.sh)"'
  - 'cp ckeditor/bender.ci.js $BUILD_PATH'
  - 'cd $BUILD_PATH && bender run -c bender.ci.js'
